all:
  vars:
    control_plane_endpoint: 192.168.60.100
    load_balancer_ip_pool:
      - 192.168.100.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.60.110, mac: 'BC:24:11:8C:05:1E', disk: sda, network_interface: eno1}
        metal1: {ansible_host: 192.168.60.111, mac: 'BC:24:11:F9:FE:6C', disk: sda, network_interface: eno1}
        metal2: {ansible_host: 192.168.60.112, mac: 'BC:24:11:3A:03:56', disk: sda, network_interface: eno1}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.60.113, mac: 'BC:24:11:41:2A:B7', disk: sda, network_interface: eno1}
